//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraSucursal
    {
        public int ID_bitacoraSucursal { get; set; }
        public int ID_sucursal { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string correo { get; set; }
        public string provincia { get; set; }
        public string distrito { get; set; }
        public string canton { get; set; }
        public System.DateTime fechaCambio { get; set; }
        public string nombre { get; set; }
        public string detalle { get; set; }
    }
}
