//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraServicio
    {
        public int ID_bitacoraServicio { get; set; }
        public int ID_servicio { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCambio { get; set; }
        public string detalle { get; set; }
    }
}
