//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraCliente
    {
        public int ID_bitacoraCliente { get; set; }
        public int ID_usuarioCliente { get; set; }
        public string correo { get; set; }
        public byte[] contraseña { get; set; }
        public Nullable<bool> asegurado { get; set; }
        public System.DateTime fechaCambio { get; set; }
    
        public virtual UsuariosCliente UsuariosCliente { get; set; }
    }
}
