//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ficha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ficha()
        {
            this.HistorialAtendidos = new HashSet<HistorialAtendido>();
        }


        [Display(Name = "Identificador")]
        public int ID_ficha { get; set; }

        [Display(Name = "Servicio")]
        public int ID_servicio { get; set; }
        [Display(Name = "Código")]
        public string codigoFicha { get; set; }
        [Display(Name = "Fecha")]
        public System.DateTime fecha { get; set; }
        [Display(Name = "Atendido")]
        public string atendido { get; set; }
        [Display(Name = "Llamado")]
        public string llamado { get; set; }
        public string agendado { get; set; }

        [Display(Name = "Tipo de ficha")]
        public string tipoFicha { get; set; }

        public int ID_usuario { get; set; }

        public virtual Servicio Servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialAtendido> HistorialAtendidos { get; set; }
    }
}
