//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HistorialAtendido
    {
        public int ID_historialAtendido { get; set; }
        public int ID_servicio { get; set; }
        public int ID_ficha { get; set; }
        public System.DateTime horaInicio { get; set; }
        public System.DateTime horaFin { get; set; }
        public int duracion { get; set; }
        public System.DateTime fecha { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [Display(Name = "Cédula de identidad")]
        
        public int ID_usuario { get; set; }
    
        public virtual Ficha Ficha { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
