//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ATECA_BDEntities : DbContext
    {
        public ATECA_BDEntities()
            : base("name=ATECA_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BitacoraServicio> BitacoraServicios { get; set; }
        public virtual DbSet<BitacoraSucursal> BitacoraSucursals { get; set; }
        public virtual DbSet<BitacoraTipos> BitacoraTipos { get; set; }
        public virtual DbSet<Ficha> Fichas { get; set; }
        public virtual DbSet<HistorialAtendido> HistorialAtendidos { get; set; }
        public virtual DbSet<Reporte> Reportes { get; set; }
        public virtual DbSet<Servicio> Servicios { get; set; }
        public virtual DbSet<Sucursale> Sucursales { get; set; }
        public virtual DbSet<TiposReporte> TiposReportes { get; set; }
        public virtual DbSet<BitacoraRol> BitacoraRols { get; set; }
        public virtual DbSet<BitacoraUsuario> BitacoraUsuarios { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int LlamarCliente(Nullable<int> iD_ficha)
        {
            var iD_fichaParameter = iD_ficha.HasValue ?
                new ObjectParameter("ID_ficha", iD_ficha) :
                new ObjectParameter("ID_ficha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LlamarCliente", iD_fichaParameter);
        }
    }
}
