//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reporte
    {
        [Display(Name = "Identificador")]
        public int ID_reporte { get; set; }

        [Display(Name = "Identificador de sucursal")]
        public int ID_sucursal { get; set; }
        public int ID_tipo { get; set; }
        public string detalle { get; set; }
        public string periodo { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Sucursale Sucursale { get; set; }
        public virtual TiposReporte TiposReporte { get; set; }
    }
}
