//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TiposReporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposReporte()
        {
            this.BitacoraTipos = new HashSet<BitacoraTipos>();
            this.Reportes = new HashSet<Reporte>();
        }
        private const string Letras =
       "^[a-zA-Z ÁÉÍÓÚáéíóú']+$";

        public int ID_tipo { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [StringLength(35, MinimumLength = 10,
        ErrorMessage = "El nombre del tipo de reporte debe contener entre 10 y 35 caractéres de longitud")]
        [DataType(DataType.Text)]
        [RegularExpression(Letras, ErrorMessage = "Solo se admiten letras")]
        public string nombreTipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraTipos> BitacoraTipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reporte> Reportes { get; set; }
    }
}
