//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosFuncionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuariosFuncionario()
        {
            this.BitacoraFuncionarios = new HashSet<BitacoraFuncionario>();
            this.HistorialAtendidos = new HashSet<HistorialAtendido>();
        }
    
        public int ID_usuarioFuncionario { get; set; }
        public string nombre { get; set; }
        public string cedula { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string apellidos { get; set; }
        public string correo { get; set; }
        public byte[] contraseña { get; set; }
        public string cargo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraFuncionario> BitacoraFuncionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialAtendido> HistorialAtendidos { get; set; }
    }
}
