//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoATECA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.BitacoraUsuarios = new HashSet<BitacoraUsuario>();
            this.HistorialAtendidos = new HashSet<HistorialAtendido>();
        }

        public int ID_usuario { get; set; }

        [Required(ErrorMessage = "Campo requerido")]
        [StringLength(15, MinimumLength = 3,
        ErrorMessage = "El nombre debe estar entre 2 y 15 caractéres")]
        [DataType(DataType.Text)]
        [RegularExpression("^[a-zA-ZáéíóúÁÉÍÓÚ]+$", ErrorMessage="Solo se admiten letras")]
        public string nombre { get; set; }
        public string cedula { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string correo { get; set; }
        public string contraseña { get; set; }
        public Nullable<int> ID_rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraUsuario> BitacoraUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialAtendido> HistorialAtendidos { get; set; }
        public virtual Role Role { get; set; }
    }
}
